name: engage_sante
services:
  # Base de donnée Postgres
  db:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  # Container d'application Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  postgres_data: