name: Build, Deploy and Test

on:
  push:
    branches:
        - develop
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        PORT: 8000
        POSTGRES_VERSION: latest
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: docker-compose -f docker-compose.test.yml build

      - name: Deploy
        run: docker-compose -f docker-compose.test.yml up -d
    
      - name: Check run 
        run: docker-compose -f docker-compose.test.yml ps

      - name: Run tests
        run: docker-compose -f docker-compose.test.yml exec -T web python manage.py test
